### ISSUE TITLE
Typescript tutorial doesn't work.

### ISSUE THREAD

**Issue by woosanghun** [simoncomputing/grok#11] opened 2016-12-05 02:14 UTC
Nothing comes out on the console.   It only says "exec".

This is on a Windows machine, IE11.

**Comment by lazyvar** [comment] 2016-12-05 13:47
caused by property 'includes' not found on type Object

**Comment by lazyvar** [comment] 2016-12-05 14:15
fixed in 7734479

**Closed as completed by lazyvar** 2016-12-05 14:15 UTC
Labels: bug
